### ISSUE TITLE
Unitphp version ? also unitphp library is missing

### ISSUE THREAD

**Issue by flik** [D-system/UnitedJapan#1]
Can you add some instructions ?

So we could setup the project and run the unittest cases.

**Comment by flik** [comment]
I also need database script

**Comment by flik** [comment]
Jan2018@adminxA MINGW32 /d/xampp/htdocs/UnitedJapan (master)
$ ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php --testdox ./tests

Fatal error: Class 'Zend_Test_PHPUnit_ControllerTestCase' not found in D:\xampp\htdocs\UnitedJapan\tests\application\controllers\IndexControllerTest.php on line 3
PHP Fatal error:  Class 'Zend_Test_PHPUnit_ControllerTestCase' not found in D:\xampp\htdocs\UnitedJapan\tests\application\controllers\IndexControllerTest.php on line 3

**Comment by D-system** [comment]
The project never really worked.
It's a 6 years old project not finished using the previous major version of the Zend framework.
